safe: true
lsi: false
highlighter: rouge
markdown: kramdown
gems: [jekyll-paginate]
url: http://wp-cli.org
permalink: /blog/:title.html
paginate: 10
paginate_path: /blog/page:num
include:
  - _s
exclude:
  - bin
  - vendor
  - Phakefile.php
  - README.md
navigation:
- text: Commands
  url: /commands/
- text: Configuration
  url: /config/
- text: Docs
  url: /docs/
- text: Blog
  url: /blog/
  layout: post
- text: Packages
  url: /package-index/
- text: RESTful WP-CLI
  url: /restful/
languages:
- label: English
  iso-alpha2: en
  path: /
- label: Japanese
  iso-alpha2: ja
  path: /ja/
- label: Français
  iso-alpha2: fr
  path: /fr/
- label: Português (Brasil)
  iso-alpha2: br
  path: /br/
- label: Türkçe
  iso-alpha2: tr
  path: /tr/
- label: Deutsch
  iso-alpha2: de
  path: /de/
- label: नेपाली
  iso-alpha2: ne
  path: /ne/
- label: ελληνικά
  iso-alpha2: gr
  path: /gr/
- label: Italiano
  iso-alpha2: it
  path: /it/
